---
abstract: 'A collection of tools for the analysis of CLIP-Seq data.'
author:
  - 'Emmanouil "Manolis" Maragkakis <mns.marag@gmail.com>, Panagiotis Alexiou <pan.alexiou@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CLIPSeqTools
requires:
  DBD::SQLite: '0'
  DBI: '0'
  Data::Table: '0'
  File::Path: '0'
  File::Spec: '0'
  File::Temp: '0'
  GenOO: v1.4.2
  GenOO::Data::File::BED: '0'
  GenOO::Data::File::SAM: '0'
  GenOO::GeneCollection::Factory: '0'
  GenOO::RegionCollection::Factory: '0'
  GenOO::TranscriptCollection::Factory: '0'
  GenOOx::Data::File::SAMbwa: '0'
  GenOOx::Data::File::SAMstar: '0'
  Getopt::Long: '0'
  List::Util: '0'
  Math::Round: '0'
  Modern::Perl: '0'
  PDL: '2.007'
  Pod::Usage: '0'
  Try::Tiny: '0'
  autodie: '0'
resources:
  bugtracker: https://github.com/palexiou/GenOO-CLIP/issues
  homepage: https://github.com/palexiou/GenOO-CLIP
  repository: https://github.com/palexiou/GenOO-CLIP.git
version: 0.0.1
